name: 'scoped-actions'
description: 'Run GitHub actions only on necessary scopes'
inputs:
  run-step:
    description: 'Command to be run, can specify many commands, e.g, run-1: npm install, run-2 npm start'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
