name: 'scoped-actions'
description: 'Run GitHub actions only on necessary scopes'
inputs:
  files:
    description: 'Changed and added files'
    required: true
  sn:
    description: 'Command to be run in order, can specify many commands, e.g, s1: npm install, s2 npm start'
    required: false
  eslintTarget:
    description: 'Target eslint files'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
