on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run scoped actions
        uses: ./ # Uses an action in the root directory
        with:
          $0: 'npm install'
          $1: 'npm run prettier'
          $2: 'npm run lint'
      # Use the output from the `hello` step
