on: [push, pull_request]

jobs:
  run-test:
    runs-on: ubuntu-latest
    name: Run test, lint tool, code formatter on changed files and workspaces
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # get git diff
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: csv
          token: ${{ github.token }}
      - name: Run scoped actions
        uses: DukeManh/scoped-actions@actions
        with:
          files: ${{ steps.files.outputs.added_modified}}
          eslintTarget: '**/*.{jsx,tsx,ts,js}' # eslint target files
          # Run commands in order, s0 -> s1 -> ... -> sn
          s0: 'npm install'
          s1: 'npm run prettier-check'
          s2: 'npm run lint'
